OSS work: sdk and cli support for training retriever, e2e, and qa-gen, license
arcee-ai/DALM pull request #33
Opened 2023-09-17 20:19 UTC by Ben-Epstein

* add global CLI `dalm` that can be called post install
* support train e2e
* support retriever only training
* support qa gen on user dataset
* update documentation everywhere for how to use `dalm` cli
* fix code/mypy errors not previously handled
* fix new linting/typing issues not caught because of argparse
* add license

closes #22
closes #21 
closes #15

2023-09-19 22:26 UTC, shamanez requested changes

2023-09-20 00:20 UTC, Ben-Epstein commented on dalm/cli.py
> +    train_e2e(
I'm not sure what you mean? It's just the 1 function. This is identical to how we have it with argparse https://github.com/arcee-ai/DALM/blob/main/dalm/training/rag_e2e/train_rage2e.py#L58-L211

Why is this confusing but argparse isn't?

2023-09-20 00:22 UTC, Ben-Epstein commented on README.md
> +dalm train-retriever-only "BAAI/bge-large-en" "./dalm/datasets/toy_data_train.csv" \
okay

2023-09-20 00:53 UTC, shamanez approved these changes

2023-09-20 01:04 UTC, merged